plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.2'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.demo'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation "com.google.zxing:core:3.5.0"
    implementation 'com.google.zxing:javase:3.5.0'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

task buildUi(type: Exec) {
    workingDir "${projectDir}/ui"
    commandLine 'yarn', 'build'
    doLast {
        println "UI build completed!"
    }
}

task cleanBuild(type: GradleBuild) {
    tasks = ['clean', 'buildUi', 'build']
}

bootJar {
    from('./ui/dist/ui') {
        into 'public'
    }
}

bootRun {
    systemProperties = System.properties
}

